language: java

jdk:
  - openjdk8

install:
  - mvn test-compile -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
  - mvn test jacoco:report

after_success:
  - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false